title: Lightningspirit's Blog
email: lightningspirit+blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programmer, Hacker, Architect, Entrepreneur, Story Teller, Musician.
  Mathematics and Astrophysics passionate. User Experience lover.
  I'm just a spiritual being having a human experience.
copyright_name: "lightningspirit"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lightningspir.it" # the base hostname & protocol for your site, e.g. http://example.com
author: lightningspirit
permalink: none

# Social Media
twitter_username: wpforms
github_username: lightningspirit
facebook_username: lightningspirit
email_username: lightningspirit+blog@gmail.com

# Avatar
avatar: assets/images/avatar.jpg

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-106952457-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

paginate: 5

exclude: 
  - README.md 
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-paginate

sass:
    style: compressed
